name: Scheduled Merge Remote Action
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: remapped
          fetch-depth: 0 

      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: HibiscusMC/HMCCosmetics
          upstream-branch: remapped
          branch: remapped
